/**
 * Sub-Transaction Types
 *
 * This is the ONE canonical SubTransaction type used throughout the system.
 * It combines:
 * - Planning info (from the planner): dependencies, description, agent role, safety checks
 * - Execution info (filled at runtime): worktree path, base commit, end commit, status, timestamps
 * - Safety gate results: structured results from running safety checks
 *
 * This unified type eliminates the previous split between "planner SubTransaction" and
 * "checkpoint SubTransaction" - now there is exactly one concept.
 */

// ============================================================================
// Safety Check Types
// ============================================================================

/**
 * Result of a single safety check command execution
 */
export interface SafetyCheckResult {
	/** The command that was run (e.g. "pnpm test") */
	cmd: string
	/** Exit code from the command (0 = success) */
	exitCode: number
	/** Duration in milliseconds */
	durationMs: number
	/** Last 2KB of stdout */
	stdoutTail: string
	/** Last 2KB of stderr */
	stderrTail: string
}

/**
 * Aggregate result of running all safety checks for a sub-transaction
 */
export interface SafetyGate {
	/** True if ALL checks passed (exit code 0) */
	ok: boolean
	/** Individual results for each check */
	results: SafetyCheckResult[]
	/** If not ok, which command failed first */
	failedAt?: string
}

// ============================================================================
// Step Types (for planner-generated action sequences)
// ============================================================================

/**
 * A discrete step/action within a sub-transaction
 * Generated by the planner to describe what the agent should do
 */
export interface Step {
	/** Type of action */
	type: "edit_file" | "run_command" | "read_file"
	/** Target of the action (file path or command) */
	target: string
	/** Description of what to do */
	action: string
}

// ============================================================================
// Sub-Transaction Types
// ============================================================================

/**
 * Sub-transaction lifecycle status
 *
 * - PENDING: Created by planner, not yet started
 * - RUNNING: Execution in progress (worktree created, agent working)
 * - COMMITTED: Successfully completed and merged
 * - ABORTED: Failed (safety check, merge conflict, error, or timeout)
 */
export type SubTransactionStatus = "PENDING" | "RUNNING" | "COMMITTED" | "ABORTED"

/**
 * Failure reason categories
 */
export type SubTransactionFailureKind = "MERGE_CONFLICT" | "SAFETY_FAIL" | "RUNTIME_ERROR" | "TIMEOUT"

/**
 * Unified SubTransaction type
 *
 * This is the canonical representation used everywhere in the system:
 * - Planner outputs this type (with execution fields undefined)
 * - PlanExecutor fills in execution fields during runtime
 * - Control-Plane persists this to the database
 * - UI displays this for visualization
 */
export interface SubTransaction {
	// ========================================================================
	// Identity
	// ========================================================================

	/** Unique identifier for this sub-transaction */
	id: string

	/** Parent transaction ID (the top-level task transaction) */
	parentTxId?: string

	// ========================================================================
	// Planning Info (from LLM planner)
	// ========================================================================

	/** Short title for the sub-transaction */
	title?: string

	/** Detailed description of what this sub-transaction does */
	description?: string

	/** Agent specialization type */
	agentType?: "coder" | "tester" | "reviewer" | "general"

	/** The prompt/task for this sub-transaction */
	prompt?: string

	/** IDs of sub-transactions that must complete before this one */
	dependsOn?: string[]

	/** Commands to run as safety checks before commit (e.g. ["pnpm test", "pnpm lint"]) */
	safetyChecks?: string[]

	/** Discrete steps/actions planned for this sub-transaction (planner-specific) */
	steps?: Step[]

	/** Whether this sub-transaction can run in parallel with others in its group */
	parallel?: boolean

	// ========================================================================
	// Execution Info (filled at runtime)
	// ========================================================================

	/** Git commit hash at the start of this sub-transaction */
	baseCommit?: string

	/** Git commit hash at the end of this sub-transaction (after commit) */
	endCommit?: string

	/** Current status in the lifecycle */
	status: SubTransactionStatus

	/** Path to the git worktree for this sub-transaction */
	worktreePath?: string

	// ========================================================================
	// Safety Gate (filled after checks run)
	// ========================================================================

	/** Results of running safety checks */
	safetyGate?: SafetyGate

	// ========================================================================
	// Failure Info
	// ========================================================================

	/** If status is ABORTED, details about the failure */
	failure?: {
		kind: SubTransactionFailureKind
		message: string
	}

	// ========================================================================
	// Timestamps
	// ========================================================================

	/** Unix timestamp when this sub-transaction was created */
	createdAt: number

	/** Unix timestamp when execution started */
	startedAt?: number

	/** Unix timestamp when execution ended (success or failure) */
	endedAt?: number
}

// ============================================================================
// Retry Policy Types
// ============================================================================

/**
 * Policy for handling sub-transaction failures
 *
 * - RETRY_SAME: Retry the same sub-transaction with same parameters
 * - REPLAN: Go back to planner and generate new sub-transactions
 * - SKIP: Skip this sub-transaction and continue with dependents
 * - ABORT_TASK: Stop the entire task immediately
 */
export type RetryPolicy = "RETRY_SAME" | "REPLAN" | "SKIP" | "ABORT_TASK"

/**
 * Structured record of a sub-transaction failure
 * Used for logging, analysis, and retry decisions
 */
export interface SubTransactionFailure {
	/** ID of the failed sub-transaction */
	subTxId: string

	/** Failure details */
	failure: SubTransaction["failure"]

	/** Safety gate results if failure was due to safety checks */
	safetyGate?: SafetyGate

	/** The retry policy that was applied */
	retryPolicy?: RetryPolicy
}

// ============================================================================
// Plan Types (moved from planner/types.ts for consistency)
// ============================================================================

/**
 * A complete execution plan generated by the planner
 */
export interface Plan {
	/** Human-readable title for the plan */
	title: string

	/** Summary of what the plan will accomplish */
	summary: string

	/** Ordered list of sub-transactions to execute */
	subTransactions: SubTransaction[]

	/** When the plan was generated */
	createdAt: number
}
